SELECT * FROM amazon_tweets
SELECT * FROM apple_tweets
SELECT * FROM goog_tweets
SELECT * FROM googl_tweets
SELECT * FROM microsoft_tweets
SELECT * FROM tesla_tweets
SELECT * FROM company_info
SELECT * FROM company_values
SELECT * FROM tweet_2015
SELECT * FROM tweet_2016
SELECT * FROM tweet_2017
SELECT * FROM tweet_2018
SELECT * FROM tweet_2019